#!/bin/bash
# This script is created by Yannis Tsopokis and is under the AGPL v3
basename=$(basename "$1" .pdf)
#pdf2ps -sDEVICE=psgray "${basename}.pdf"  #older version
pdf2ps -sDEVICE=ps2write -dProcessColorModel=/DeviceGray -dColorConversionStrategy=/Gray -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH  "${basename}.pdf"
ps2pdf "${basename}.ps" "${basename}-bw.compressed.pdf"
rm "${basename}.ps"
